spring.application.name=TodoApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/todoapp
spring.datasource.username=postgres
spring.datasource.password=gandhi1202
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
